# Generated by Django 4.0.3 on 2022-04-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='be_a_customer',
            new_name='is_seller',
        ),
    ]
