# Generated by Django 4.0.3 on 2022-04-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
