# Generated by Django 4.0.3 on 2022-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_comments_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reviews',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
