# Generated by Django 4.0.3 on 2022-04-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comments_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reviews',
            new_name='rate',
        ),
    ]
