# Generated by Django 4.0.3 on 2022-04-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_reviews_comments_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
